### ISSUE TITLE
Cant get working with nodeJS chaincode.

### ISSUE THREAD

**Issue by simonmullaney** [wearetheledger/fabric-mock-stub#14]
Hey guys - thanks for this repo, its really helpful!

I'm struggling trying get it to work with my chaincode written in javascript though.

Do you know what steps I have to carry out in order to get it working on javascript. I'm thinking of forking & implementing the required changes so that people can test both .ts and .js chaincode!

Thanks!

**Comment by sneljo1** [comment]
I don't think we ever tested this. But it transpiles to vanilla js, with added typescript types. So in theory, it should also work when using vanilla js.

What is the issue you are having?

**Comment by simonmullaney** [comment]
Ok so I cloned the repo and then changed the `TestChaincode.ts` file to `TestChaincode.js`

This was giving me an error:

> SyntaxError: Unexpected token export

I then took away the export token and exported the class using module.exports as shown below:

```
// used to be:
//export class TestChaincode {
class TestChaincode {

    // The Init method is called when the Smart Contract 'fabcar' is instantiated by the blockchain network
    // Best practice is to have any Ledger initialization in separate function -- see initLedger()
    async Init(stub) {
.
.
. 
.

    async crossChaincode(stub, args) {

        const response = await stub.invokeChaincode("pingcode", ["ping"], "mychannel");

        return response.payload;
    }
}
module.exports = TestChaincode
```

Now if i run `npm run test` I get the following error:

> ERROR [lib/chaincode.js] uncaughtException: TestChaincode_1.TestChaincode is not a constructor

**Comment by sneljo1** [comment]
Are you using a transpiler? Or are you just using the plain node?

**Comment by simonmullaney** [comment]
I'm using node, i haven't changed the the `npm run test` script  which is still running `mocha -r ts-node/register test/**/*.spec.ts --reporter spec`

**Comment by simonmullaney** [comment]
Changing the code to below fixes the issue:

```
// used to be:
//export class TestChaincode {
class TestChaincode {

    // The Init method is called when the Smart Contract 'fabcar' is instantiated by the blockchain network
    // Best practice is to have any Ledger initialization in separate function -- see initLedger()
    async Init(stub) {
.
.
. 
.

    async crossChaincode(stub, args) {

        const response = await stub.invokeChaincode("pingcode", ["ping"], "mychannel");

        return response.payload;
    }
}
exports.TestChaincode = TestChaincode;
```

**Comment by sneljo1** [comment]
Perhaps you're tsconfig was targetting the wrong javascript version. Exports should work when targetting es6 or up.
