### ISSUE TITLE
MockStateQueryIterator is NOT the same as StateQueryIterator

### ISSUE THREAD

**Issue by ethan-fox** [wearetheledger/fabric-mock-stub#15]
Hello! I represent a group at IBM working on a project leveraging HLF 1.2 using Node.JS chaincode, and we're using your Mock Stub class for our testing suite.  It's run great so far, however all of our tests mysteriously failed when we started running test cases that leveraged the Shim Library's `StateQueryIterator`.  Originally we thought it was something on our end, but what we realized was that your MockStub class `MockStateQueryIterator` is actually constructed differently.  This has caused issues for testing because we now need to write in code that will *only* be used to pass the test cases.

For example, the following object gets created when we initialize a `MockStataeQueryIterator` via `stub.getQueryResult()` in the context of our testing suite:

    MockStateQueryIterator {
      data: 
       [ MockKeyValue {
           key: 'action1',
           value: <Buffer 7b 22 61 73 73 65  ... > } ],
      currentLoc: 0,
      closed: false }

However, when we run the chaincode in the context of a true Hyperledger Fabric Network, the following `StateQueryIterator` is created (in the exact same location in the code):

```
StateQueryIterator {
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  type: 'QUERY',
  handler: 
   (I'll save us all the trouble and not post the ChaincodeSupportClient metadata),
  channel_id: 'mychannel',
  txID: 'b0401eefc2a1bd651f0d551beed392a6ed4079571ea992b2d96109ef64fd49e9',
  response: 
   { results: [ [Object] ],
     has_more: false,
     id: '89547929-ca59-4e93-92ee-46ad8ecc957a',
     metadata: 
      ByteBuffer {
        buffer: <Buffer >,
        offset: 0,
        markedOffset: -1,
        limit: 0,
        littleEndian: false,
        noAssert: false } },
  currentLoc: 0 }
```

Essentially, we're running a rich query to determine if an object with a certain value already exists on the chain, and to do this we need to check the iterator to see if that item exists.  However, in the context of both types of objects, what we're looking for exists in two different spots.  The code snippet below details the temporary solution we've found to the problem:

```
const queryString = `{"selector":{"assetId":"${identifier}"}}`;
const queryResult = await stub.getQueryResult(queryString);
           
let validate;

switch(queryResult.constructor.name){
  case 'MockStateQueryIterator':
    validate = queryResult.data.length;
    break;
  case 'StateQueryIterator':
    validate = queryResult.response.results.length;
    break;
}

if (validate === 0) {
                Chaincode.throwJsonError(`Asset with id ${identifier} does not exist.`)
}
```

It's very poor coding practice to include code specifically for passing test cases, and it won't get deployed into production in it's current state, however currently it's the quickest fix to the problem.  Internally we're determining the best way to move forward here; so far the best option appears to be to create another "Mock" layer where we transform the iterator, regardless of whether or not it's some `StateQueryIterator` or `MockStateQueryIterator` and put it into it's own object or something, at which point our main method can take care of checking for the right properties.

Depending on what we do we may end up making a pull req to your repo with a fix to the problem, but in the meantime we figured we'd bring it up to your team so you can look into it and work on it yourselves.

Thanks for all your hard work!

**Comment by sneljo1** [comment]
I had mostly written this by first following the types and then browsing through the shim to see if I forgot something. So, I must've overlooked that. I'm pusing this in 3.0.1 in a few minutes.
