### ISSUE TITLE
mockPeerChaincode not working

### ISSUE THREAD

**Issue by diestrin** [wearetheledger/fabric-mock-stub#2]
First of all, thank you for this project, it has been really helpful to make the chaincode migrations from Go to TS <3

But I found a problem with `mockPeerChaincode`, trying to make a chaincode invoke another one. Looks like `invokables` is [not being initialized](https://github.com/wearetheledger/fabric-mock-stub/blob/master/src/ChaincodeMockStub.ts#L47) anywhere, and also the `invokeChaincode` functions is [calling the wrong function](https://github.com/wearetheledger/fabric-mock-stub/blob/master/src/ChaincodeMockStub.ts#L184) `otherStub.MockInvoke` and the correct one is `otherStub.mockInvoke`.

If I get some time in the near future I'll submit a PR with the fixes, just reporting these for now.

**Comment by sneljo1** [comment]
Thanks for reporting, this feature isn't included in the tests, so I'm not suprised it isn't working.
