### ISSUE TITLE
queryByPartialKey

### ISSUE THREAD

**Issue by 6lick** [wearetheledger/fabric-mock-stub#22]
the mockstub queryByPartialKey accepts a string as the second parm, however real stub throws an error it must be a string array and the mockShim throws an error when I pass an array. 

Using fabric-shim v1.4.1

**Comment by sneljo1** [comment]
I'm following their type definitions so that would be strange. Are you maybe trying to use the querybypartialkey for private data? This one accepts a string as second param.
